"""update question model

Revision ID: 03ed0aacc984
Revises: 1a1bf58ab381
Create Date: 2025-01-15 15:10:18.358462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03ed0aacc984'
down_revision: Union[str, None] = '1a1bf58ab381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_request', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('question_request', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'question_request', 'user_profile', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_request', type_='foreignkey')
    op.alter_column('question_request', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('question_request', 'user_id')
    # ### end Alembic commands ###
