"""add user role rating and tasks

Revision ID: 163ae9306405
Revises: c3c28edb35a8
Create Date: 2024-11-12 14:38:34.368358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163ae9306405'
down_revision: Union[str, None] = 'c3c28edb35a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles_rating',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('plus', sa.Integer(), nullable=True),
    sa.Column('minus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('user_roles_tasks',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('done_create_task', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles_tasks')
    op.drop_table('user_roles_rating')
    # ### end Alembic commands ###
