"""update status task and delete status task response model

Revision ID: 1ac7c218e020
Revises: 03ed0aacc984
Create Date: 2025-01-17 15:07:22.487942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ac7c218e020'
down_revision: Union[str, None] = '03ed0aacc984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_responses', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_responses', sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', name='taskresponsestatusenum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
