"""add CASCADE delete to acc

Revision ID: 339a93c24f86
Revises: 40b191a46af4
Create Date: 2024-12-30 17:42:01.594658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339a93c24f86'
down_revision: Union[str, None] = '40b191a46af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customer_profile_auth_id_fkey', 'customer_profile', type_='foreignkey')
    op.create_foreign_key(None, 'customer_profile', 'auth', ['auth_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('executor_profile_auth_id_fkey', 'executor_profile', type_='foreignkey')
    op.create_foreign_key(None, 'executor_profile', 'auth', ['auth_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_roles_auth_id_fkey', 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'auth', ['auth_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key('user_roles_auth_id_fkey', 'user_roles', 'auth', ['auth_id'], ['id'])
    op.drop_constraint(None, 'executor_profile', type_='foreignkey')
    op.create_foreign_key('executor_profile_auth_id_fkey', 'executor_profile', 'auth', ['auth_id'], ['id'])
    op.drop_constraint(None, 'customer_profile', type_='foreignkey')
    op.create_foreign_key('customer_profile_auth_id_fkey', 'customer_profile', 'auth', ['auth_id'], ['id'])
    # ### end Alembic commands ###
