"""add uniq profile model

Revision ID: 53b93a03f99e
Revises: 
Create Date: 2025-01-09 16:09:05.703322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b93a03f99e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phoneNumber', sa.String(), nullable=False),
    sa.Column('otpCode', sa.String(length=6), nullable=True, comment='Код одноразового пароля для подтверждения авторизации'),
    sa.Column('otpExpiry', sa.DateTime(), nullable=True, comment='Время истечения срока действия OTP'),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания записи'),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата последнего обновления записи'),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Enum('ONE_MONTH', 'THREE_MONTHS', 'TWELVE_MONTHS', name='subscriptionperiodenum'), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('about_myself', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auth_id'], ['auth.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.NUMERIC(), nullable=False),
    sa.Column('term_from', sa.DateTime(), nullable=False),
    sa.Column('term_to', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'PROCESSING', 'COMPLETED', 'CANCELLED', name='tasksstatusenum'), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_use', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['executor_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='taskresponsestatusenum'), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('response_date', sa.DateTime(), nullable=True),
    sa.Column('room_uuid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['executor_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_responses')
    op.drop_table('reviews')
    op.drop_table('user_roles')
    op.drop_table('tasks')
    op.drop_table('user_profile')
    op.drop_table('subscriptions')
    op.drop_table('roles')
    op.drop_table('auth')
    # ### end Alembic commands ###
