"""add token to auth model

Revision ID: 721a236ee7fa
Revises: 5482e0038fca
Create Date: 2025-01-28 12:31:07.592467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '721a236ee7fa'
down_revision: Union[str, None] = '5482e0038fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth', 'token')
    # ### end Alembic commands ###
