"""add location to task model

Revision ID: 9204bfd95f34
Revises: e9aecef55e92
Create Date: 2024-11-13 16:21:35.533339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9204bfd95f34'
down_revision: Union[str, None] = 'e9aecef55e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('location', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'location')
    # ### end Alembic commands ###
