"""add code Creadet at time

Revision ID: 98282f0f0bb1
Revises: 5422bdfb96c5
Create Date: 2024-11-07 19:43:51.416023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98282f0f0bb1'
down_revision: Union[str, None] = '5422bdfb96c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('codeCreatedAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'codeCreatedAt')
    # ### end Alembic commands ###
