"""add is use role 

Revision ID: 9ea763ef766f
Revises: b7d063d45c90
Create Date: 2024-11-12 16:08:34.291621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea763ef766f'
down_revision: Union[str, None] = 'b7d063d45c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('is_use', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_roles', 'is_use')
    # ### end Alembic commands ###
