"""add user_id for tasks

Revision ID: e9aecef55e92
Revises: 9ea763ef766f
Create Date: 2024-11-13 15:42:08.038710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9aecef55e92'
down_revision: Union[str, None] = '9ea763ef766f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('term_from', sa.DateTime(), nullable=False))
    op.add_column('tasks', sa.Column('term_to', sa.DateTime(), nullable=False))
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'user_id')
    op.drop_column('tasks', 'term_to')
    op.drop_column('tasks', 'term_from')
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###
