"""fixing room_uuid 

Revision ID: f2cc48c41a5e
Revises: 255ad73f7f79
Create Date: 2025-01-06 19:07:16.404656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2cc48c41a5e'
down_revision: Union[str, None] = '255ad73f7f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_responses', sa.Column('room_uuid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_responses', 'room_uuid')
    # ### end Alembic commands ###
