"""add new model subscription

Revision ID: ff0ee2e1e404
Revises: 53b93a03f99e
Create Date: 2025-01-11 14:04:54.289297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff0ee2e1e404'
down_revision: Union[str, None] = '53b93a03f99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('subscriptions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('subscriptions', sa.Column('plan_id', sa.Integer(), nullable=False))
    op.add_column('subscriptions', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.add_column('subscriptions', sa.Column('end_date', sa.DateTime(), nullable=False))
    op.add_column('subscriptions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'subscriptions', 'user_profile', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subscriptions', 'subscriptions_plan', ['plan_id'], ['id'], ondelete='CASCADE')
    op.drop_column('subscriptions', 'period')
    op.drop_column('subscriptions', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('period', postgresql.ENUM('ONE_MONTH', 'THREE_MONTHS', 'TWELVE_MONTHS', name='subscriptionperiodenum'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'is_active')
    op.drop_column('subscriptions', 'end_date')
    op.drop_column('subscriptions', 'start_date')
    op.drop_column('subscriptions', 'plan_id')
    op.drop_column('subscriptions', 'user_id')
    op.drop_table('subscriptions_plan')
    # ### end Alembic commands ###
